/*
 * Copyright (C) 2011-2016 Intel Corporation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *   * Neither the name of Intel Corporation nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include "ias_ra.h"
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

// This whole file is used as simulation of the interfaces to be
// delivered an attestation server.

#define UNUSED(expr)  \
    do {              \
        (void)(expr); \
    } while (0)

#if !defined(SWAP_ENDIAN_DW)
#define SWAP_ENDIAN_DW(dw)                                  \
    ((((dw)&0x000000ff) << 24) | (((dw)&0x0000ff00) << 8) | \
     (((dw)&0x00ff0000) >> 8) | (((dw)&0xff000000) >> 24))
#endif
#if !defined(SWAP_ENDIAN_32B)
#define SWAP_ENDIAN_32B(ptr)                               \
    {                                                      \
        unsigned int temp = 0;                             \
        temp = SWAP_ENDIAN_DW(((unsigned int *)(ptr))[0]); \
        ((unsigned int *)(ptr))[0] =                       \
            SWAP_ENDIAN_DW(((unsigned int *)(ptr))[7]);    \
        ((unsigned int *)(ptr))[7] = temp;                 \
        temp = SWAP_ENDIAN_DW(((unsigned int *)(ptr))[1]); \
        ((unsigned int *)(ptr))[1] =                       \
            SWAP_ENDIAN_DW(((unsigned int *)(ptr))[6]);    \
        ((unsigned int *)(ptr))[6] = temp;                 \
        temp = SWAP_ENDIAN_DW(((unsigned int *)(ptr))[2]); \
        ((unsigned int *)(ptr))[2] =                       \
            SWAP_ENDIAN_DW(((unsigned int *)(ptr))[5]);    \
        ((unsigned int *)(ptr))[5] = temp;                 \
        temp = SWAP_ENDIAN_DW(((unsigned int *)(ptr))[3]); \
        ((unsigned int *)(ptr))[3] =                       \
            SWAP_ENDIAN_DW(((unsigned int *)(ptr))[4]);    \
        ((unsigned int *)(ptr))[4] = temp;                 \
    }
#endif

// Simulates the attestation server function for verifying the quote produce by
// the ISV enclave. It doesn't decrypt or verify the quote in
// the simulation.  Just produces the attestaion verification
// report with the platform info blob.
//
// @param p_isv_quote Pointer to the quote generated by the ISV
//                    enclave.
// @param pse_manifest Pointer to the PSE manifest if used.
// @param p_attestation_verification_report Pointer the outputed
//                                          verification report.
//
// @return int

int ias_verify_attestation_evidence(
    sgx_quote_t *p_isv_quote, uint8_t *pse_manifest,
    ias_att_report_t *p_attestation_verification_report) {
    int ret = 0;

    // unused parameters
    UNUSED(pse_manifest);

    if ((NULL == p_isv_quote) || (NULL == p_attestation_verification_report)) {
        return -1;
    }

    return (ret);
}

// Simulates retrieving the SIGRL for upon the SP request.
//
// @param gid Group ID for the EPID key.
// @param p_sig_rl_size Pointer to the output value of the full
//                      SIGRL size in bytes. (including the
//                      signature).
// @param p_sig_rl Pointer to the output of the SIGRL.
//
// @return int

int ias_get_sigrl(const sgx_epid_group_id_t gid, uint32_t *p_sig_rl_size,
                  uint8_t **p_sig_rl) {
    int ret = 0;

    UNUSED(gid);

    do {
        if (NULL == p_sig_rl || NULL == p_sig_rl_size) {
            ret = -1;
            break;
        }
        *p_sig_rl_size = 0;
        *p_sig_rl = NULL;
        // we should try to get sig_rl from an attestation server
        break;
    } while (0);

    return (ret);
}

// Used to simulate the enrollment function of an attestation server.  It only
// gives back the SPID right now. In production, the enrollment
// occurs out of context from an attestation attempt and only
// occurs once.
//
//
// @param sp_credentials
// @param p_spid
// @param p_authentication_token
//
// @return int

int ias_enroll(int sp_credentials, sgx_spid_t *p_spid,
               int *p_authentication_token) {
    UNUSED(sp_credentials);
    UNUSED(p_authentication_token);

    if (NULL != p_spid) {
        //memcpy_s(p_spid, sizeof(sgx_spid_t), &g_sim_spid, sizeof(sgx_spid_t));
    } else {
        return (1);
    }
    return (0);
}
